### ISSUE TITLE
mobile typing is very laggy with canvas & new flying textarea

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#113]
I'm getting up to a second of delay before the characters appear, also sometimes they are duplicated.

**Comment by c-probably-archived20260718** [comment]
Laggy
- Chrome Android (62)
- Firefox Android (55)

Slightly laggy
- Firefox Desktop (56, 57) (issue is probably the canvas, not the textarea)

Fine
- Safari * (11)
