### ISSUE TITLE
[canvas] zoom not considered when moving soft keyboard input box

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#120]
so it goes way off-screen when you move the cursor to the right half.

**Comment by MightyPork** [comment]
this is the last canvas issue that's stopping the merge I think...
maybe just disable the input box movement if screen is zoomed to fit?

**Comment by c-probably-archived20260718** [comment]
Fixed in https://github.com/espterm/espterm-front-end/commit/2d22efc8f34718f1d9ee5b709cbefa8c0c7b07e4

**Comment by MightyPork** [comment]
confirmed
