### ISSUE TITLE
"Growl message" OSC 9 ; Pt ST

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#123]

**Comment by MightyPork** [comment]
socket message starts with marking letter 'G'

**Comment by c-probably-archived20260718** [comment]
Should work in canvas now after you do `Notification.requestPermission()` (https://github.com/espterm/espterm-front-end/commit/5cbb3ea2c9b923def5ddca9cf5eae3e3faa65a58#diff-ae7576f8239f672966b42ebabf323341R913)

**Comment by MightyPork** [comment]
it works!
but 
![screenshot_20170910_025612](https://user-images.githubusercontent.com/2041118/30245260-b6bd005c-95d3-11e7-9454-611c1da15768.png)

:(

not like i can run a ssl server on that thing and still have any RAM left for other stuff .....
