### ISSUE TITLE
Debug toolbar

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#125]
Inspired by the Status Line feature of some VT models, would show current screen and cursor state, selected modes and allow their manipulation.

- [x] Add info about mouse position and hovered cell
- [x] Add redraw buttons etc
- [x] Break-down cell attributes for easier reading (not only hex)
- [x] show debug info received from server (topic "D")
  - free heap
  - client count
  - scrolling region bounds
  - code page, Gx...
- [x] make it pretty!!
- [x] auto-open when %debugbar% is 1

**Comment by c-probably-archived20260718** [comment]
When using the canvas renderer, maybe also include a visual debug mode showing screen updates or overlaying each cell's attributes.

**Comment by c-probably-archived20260718** [comment]
As the last remaining item; what does “make it pretty” entail?

**Comment by MightyPork** [comment]
wellll that's a little abstract xD
originally i thought it'd be more visual, it's mainly for the user to debug their application code, not us.

i should add some more stuff to the Debug topic tbh, like active cursor colors

**Comment by c-probably-archived20260718** [comment]
ooooh yeah I kind of used it for debugging myself, so that's what I thought it was for xD
Yeah then there should probably be a button for _enabling_ draw debugging and it should probably be off by default

**Comment by c-probably-archived20260718** [comment]
so basically kind of like this?
<img width="613" alt="mockup" src="https://user-images.githubusercontent.com/5412095/31319738-e9bac092-ac68-11e7-926e-ae0c079f1f7a.png">

**Comment by MightyPork** [comment]
oo if you could do that, this is kinda what i imagined yeah

there should also be a toggle for Input Stream Debug¹ - sent to server (need to add this to the update word), and a button to reset the screen/parser - likewise sent to server. And a display of selected colors and other stuff that are atm not in the update word but could be...
¹
![screenshot_20171002_225500](https://user-images.githubusercontent.com/2041118/31319788-7fb917a6-ac69-11e7-9332-6c98b9616729.png)

**Comment by c-probably-archived20260718** [comment]
uhh I think it would be nicer if you could see both the input stream and the output, i.e. send that in a separate update topic

**Comment by MightyPork** [comment]
hnn well this is already implemented (it uses the screen for display). can't really store everything and send it to the front-end, maybe "last 10 bytes" or something

**Comment by MightyPork** [comment]
but like, if you add that, nothing against it, i might add back-end support later..

**Comment by c-probably-archived20260718** [comment]
yeah I mean you could just send the raw data through the websocket and let the javascripts handle it

**Comment by MightyPork** [comment]
the socket is quite slow, idk how well that'd work.. plus would need to be binary socket, bc there can be invalid utf8 pieces in it

**Comment by MightyPork** [comment]
hmm also you still don't have display and data at the same time, unless you'd open two sockets in parallel

**Comment by MightyPork** [comment]
but sending last n bytes for display in the debugbar is a neat idea, i kinda want that

there's already such a buffer in the back-end for showing context when a parse fails

**Comment by c-probably-archived20260718** [comment]
okay then I shall do a debugger makeover after I finish the more hierarchical and less interwoven ScreenLayout thing

**Comment by c-probably-archived20260718** [comment]
Merged `fancy-debug` into `work`: https://github.com/espterm/espterm-front-end/commit/78d32f7fdcf40430287cfed0bdaeb032560de2a9
