### ISSUE TITLE
Over-line style SGR 53 / 55

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#128]

**Comment by MightyPork** [comment]
back-end implemented, sent as bit 7 of character attribs byte

**Comment by c-probably-archived20260718** [comment]
Front-end implemented in canvas branch

**Comment by MightyPork** [comment]
you also have trouble sleeping? xD

it's awesome:
![screenshot_20170910_022942](https://user-images.githubusercontent.com/2041118/30245111-f4357472-95cf-11e7-865e-21d8b6ae7f80.png)
