### ISSUE TITLE
Line and Bar cursors don't clear cell when inactive, leave traces

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#129]
![screenshot_20170910_004245](https://user-images.githubusercontent.com/2041118/30244589-53ff1cb4-95c1-11e7-8b30-60e1fc570e2f.png)

(Cursor style is now configurable in terminal settings and via command, sent as bits 11..9 of attribs word)

**Comment by c-probably-archived20260718** [comment]
uhh I just pushed a commit that also added the new cursor styles and now it's got code from both. I did fix that issue in mine though, so I guess I'll use that?

**Comment by MightyPork** [comment]
uh. I guess?

but I think this is easier to read

```js
    let cursorStyle = (attributes >> 9) & 0x07;
    // 0 - Block blink, 2 - Block steady
    // 3 - Under blink, 4 - Under steady
    // 5 - I-bar blink, 6 - I-bar steady
    this.cursor.style = cursorStyle<3?'block':cursorStyle<5?'line':'bar';
    this.cursor.blinkEnable = cursorStyle === 0 || cursorStyle === 3 || cursorStyle === 5;
```

it's never 1, that's taken care of server-side.

**Comment by MightyPork** [comment]
the redraw fix works great btw!

**Comment by c-probably-archived20260718** [comment]
oh, then this is what'd be left of my decoder
```js
    let cursorShape = (attributes >> 9 & 0x07);
    let cursorStyle = cursorShape >> 1;        // I think this part makes more sense than < 3 and < 5
    let cursorBlinking = !(cursorShape & 1);

    if (cursorStyle === 0) this.cursor.style = 'block';
    else if (cursorStyle === 1) this.cursor.style = 'line';
    else if (cursorStyle === 2) this.cursor.style = 'bar';

    if (this.cursor.blinking !== cursorBlinking) {
      this.cursor.blinking = cursorBlinking;
      this.resetCursorBlink();
    }
```

**Comment by MightyPork** [comment]
yeah... with some mental gymnastics I can see how that works. can you keep the legend comment tho?

**Comment by c-probably-archived20260718** [comment]
yeah, but I see that 1 is missing and you're using < 3; are there 6 (as you said above) or 7 (as in the code) cursor styles?
Oh wait I may be misinterpreting things; when you say “it's never 1” does that mean that all numbers will shift to compensate or that 1 is unused?

**Comment by MightyPork** [comment]
numbers 1 and 7 are unused, so there are 6, blinky and steady variant of the three

**Comment by MightyPork** [comment]
however this gives me an idea to save one bit in the word - if I use number 1 or 7 to mean "cursor is hidden", then the bit number 0 of the attribs word will be free for some future use

**Comment by MightyPork** [comment]
dw about that, I'm not doing this now xD
but bits may get scarce later
