### ISSUE TITLE
Clean up the front-end directory structure

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#131]
After canvas merge, to avoid conflicts.

- move js/ and css/ into the out/ folder
- rename jssrc to js/ or javascript/
- have the build script also copy images and other files
- modify the firmware build script to retrieve the static files from here

**Comment by c-probably-archived20260718** [comment]
also, the build script currently doesn't work if the enclosing directory doesn't have an html folder.

**Comment by MightyPork** [comment]
oh it should, I changed that (maybe it didn't get into the canvas branch ...)

**Comment by c-probably-archived20260718** [comment]
Can this be done now?

Also, copy img/ to out/ and set relative paths in _head.php instead of `/`css/app.css or something

**Comment by MightyPork** [comment]
Yeah if you want to try it, go ahead. I was planning to do that tonight (was meant to work, but ehhh ... not happening )

relative paths aren't possible because on the esp they are "fancy urls" and it wouldn't work.

with the php server running, absolute paths work fine for testing...

**Comment by c-probably-archived20260718** [comment]
espterm-front-end done

**Comment by MightyPork** [comment]
oh i should update the backend, huuuh
