### ISSUE TITLE
Text editing shortcuts

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#132]
Text editing shortcuts such as

- ⌥← to go back a word (`^[b`)
- ⌥→ to go forward one word (`^[f`)
- ⌘← to go to the beginning of a line (`^A`)
- ⌘→ to go to the end of a line (`^E`)
- ⌥⌫ to delete a word (`^W`, I think)
- ⌘⌫ to delete to the beginning of a line (possibly `^U`)

are missing. I also don't know what their non-macOS counterparts are, though I suspect this'll require knowing whether or not the user agent is on macOS/iOS-with-a-hardware-keyboard.

**Comment by MightyPork** [comment]
can you try to grab what sequences those are really meant to send?
adding the commands should be possible with keymaster

I'd suggest you run hexcat (https://github.com/MightyPork/smolcat/blob/master/hexcat.c), but that won't compile on mac, so try some node hack instead i guess

**Comment by MightyPork** [comment]
also i don't think they have any non-mac counterparts.

^A and ^E seem to work with nano, that's it

**Comment by c-probably-archived20260718** [comment]
Not even ESC b and ESC f? Also, delete word sends \x17 and delete line sends \x15

**Comment by MightyPork** [comment]
CSI b should mean Repeat Last Char, CSI f is an obsolete form of CSI H and means Absolute Position. Neither does anything in editors when input from keyboard from what i can tell (but maybe ncurses doesnt like me typing it manually)

**Comment by c-probably-archived20260718** [comment]
yeah sorry I meant ESC instead of CSI

**Comment by MightyPork** [comment]
nah doesnt seem to do anything

**Comment by MightyPork** [comment]
ctrl+left, right works to move one word though

**Comment by c-probably-archived20260718** [comment]
what's ctrl+left/right sending? For me, ESC b toggles backup files and ESC f toggles multiple file buffers in nano. Vim supports them though (naturally)

**Comment by MightyPork** [comment]
```
ESC [ 1 ; 5 D ctrl left
ESC [ 1 ; 5 C ctrl right
ESC [ 1 ; 5 A ctrl up
ESC [ 1 ; 5 B ctrl down
ESC O H home
ESC O F end
ESC [ 5 ~ pg up
ESC [ 6 ~ pg dn
```

can't seem to get vim to do anything because it grabs the esc and thinks it's normal esc to change mode

**Comment by c-probably-archived20260718** [comment]
Huh. I guess you can add those, if they work? Do note though that you can't use ctrl+left/up/right/down on macOS because those are reserved for Mission Control by default
