### ISSUE TITLE
Remove theme colors from CSS

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#135]
Find a way to use the array in JS for coloring theme preview tables in other pages (Help, Terminal config).

terminal config page has a dynamic theme preview with a select box that now changes a div class name `theme-*`. Help has a static preview of the current theme.

**Comment by c-probably-archived20260718** [comment]
The color settings in the terminal config could be moved to the terminal page

**Comment by MightyPork** [comment]
:man_shrugging: I guess. and sent via Ajax
gets quite a bit cluttered in the bottom menu though ...
