### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#139]
Maybe we can abuse the zoom feature to make it fill a larger window too?

**Comment by c-probably-archived20260718** [comment]
We can, but where would you put the button? And for that matter, what items should be included in the fullscreen view? (with/without title, buttons?)

**Comment by MightyPork** [comment]
I would hide everything but the actual screen I guess? Also the blue outline possibly

(btw did you notice there's a strange transparent padding at the bottom of the canvas?)

I think there would have to be a special shortcut for this, a config option, and a DECSET command (`\e[?802h` and `\e[?802l`, perhaps).

Button would be nice, but it really gets cluttered in the bottom menu. Maybe we can hide Help and About on mobile, the view kinda sucks anyway without a desktop browser and nobody will use phone for development.

**Comment by c-probably-archived20260718** [comment]
Added in https://github.com/espterm/espterm-front-end/commit/2c3f081d994b6658f1f24bcc03b2e2ddd181533d, might be really buggy in some browsers, nothing I can really do about it

**Comment by MightyPork** [comment]
was editing the same file :C
check if I didn't mess something up with the merge

**Comment by MightyPork** [comment]
okay i'm gonna close this issue for now, seems adding commands and config option isn't really that important. works fine in Chrome!
