### ISSUE TITLE
Cursors other than block are invisible (again)

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#140]
unless i messed something up in the back-end

**Comment by c-probably-archived20260718** [comment]
probably fixed: https://github.com/espterm/espterm-front-end/commit/d5f6bf2dfa36b66f534db6aa0f03a1d07996a1b4

**Comment by MightyPork** [comment]
confirmed. but these's a new little bug (#142) ...
(or old but only now visible bc the cursors draw)
