### ISSUE TITLE
Non-block cursors leave ghosts when moving

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#142]
this happens when i move left/right (hold the cursor key). Cursor need not be blinky for this to happen. Block cursor leaves only green "ghosts" in the debug overlay (what is it?), the small cursors leave also their clones.

![screenshot_20170911_102751](https://user-images.githubusercontent.com/2041118/30265444-6b259e74-96dc-11e7-99ec-31e3d1701442.png)

![screenshot_20170911_102834](https://user-images.githubusercontent.com/2041118/30265451-6e6de99c-96dc-11e7-98c7-f709224ff1d1.png)

**Comment by c-probably-archived20260718** [comment]
### The Hitchhiker's Guide to the Debug Overlay
The debug overlay—used for debugging and looking like you're a hacker. Even in its yet short lifetime, three great myths about it have already taken the masses: some say the mysterious green cells have been updated and marked as requiring a redraw by the almighty diffing algorithm; others say the ominous magenta cells were redrawn; and cpsdqs says cells with red outlines have wide characters.

I think this bug is being caused because I'm not actually storing whether or not something was drawn to have a cursor

**Comment by c-probably-archived20260718** [comment]
Should be fixed in https://github.com/espterm/espterm-front-end/commit/5d2e8d845a86fc56b320c1aad461a8fecf61816a

**Comment by MightyPork** [comment]
looks good. but there's a new funny bug - when the cursor is right from two blink-style characters (also somewhere below and right above?), it thinks it should blink (not with the characters, but on it's own, with the slow cursor timer)

![screenshot_20170911_111010](https://user-images.githubusercontent.com/2041118/30267144-e50c433c-96e1-11e7-9deb-db01a92a8f2b.png)

**Comment by MightyPork** [comment]
oh, rather, it seems to sometimes forget about its own blink enable flag (and sometimes think it's true when it's off)

**Comment by c-probably-archived20260718** [comment]
that's actually intentional; the cursor renderer swaps the foreground and background colors, basically inverting the cell (but not the way the invert blend mode does)

wasn't it like that in the HTML renderer?

**Comment by MightyPork** [comment]
idk ... it does not blink at all when cursor blinking is enabled and there are no blinky characters

**Comment by c-probably-archived20260718** [comment]
oh I should be moving the cursor blink thing to before the didUpdate. Should be fixed in https://github.com/espterm/espterm-front-end/commit/c82a955dfcbc7567c6b1109835096a1da26318fb

**Comment by MightyPork** [comment]
just one more nitpick - switching from style "line" to "bar" produces this until the cursor moves
![screenshot_20170911_112400](https://user-images.githubusercontent.com/2041118/30267738-ce69c0c6-96e3-11e7-8915-1246ec50e6f1.png)

**Comment by c-probably-archived20260718** [comment]
https://github.com/espterm/espterm-front-end/commit/f74e689196c890d23c163919baf34e69c4794bf3

**Comment by MightyPork** [comment]
:+1: works perfectly
