### ISSUE TITLE
Optionally do not intercept F5, F12 and F11, interferes with browser shortcuts

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#146]

**Comment by c-probably-archived20260718** [comment]
Also ⌥⌘I (dev tools)

**Comment by MightyPork** [comment]
I don't think we capture _that_?

**Comment by c-probably-archived20260718** [comment]
No, but it does capture the ⌥I part of it, which means it sends ˆ every time

**Comment by MightyPork** [comment]
hnnnn

there are various options in the keymaster config, so if you wanna play with that ...
non-mac shortcuts are far easier to fix

**Comment by MightyPork** [comment]
I've implemented this for F5, F11 and F12 now. do you want to try that ⌥I ?

**Comment by MightyPork** [comment]
maybe this is related to it always binding ctrl+letter and also command+letter

```js
 /** Bind a keystroke to message */
  function bind (combo, str) {
    // mac fix - allow also cmd
    if (combo.indexOf('ctrl+') !== -1) {
      combo += ',' + combo.replace('ctrl', 'command')
    }
```

so maybe that's not the right behavior
