### ISSUE TITLE
can't type some symbols on Android

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#151]
:man_shrugging: it just doesn't get sent at all

**Comment by c-probably-archived20260718** [comment]
can you check for any other keys that aren't sent?

**Comment by MightyPork** [comment]
`. , * & + ( ) / " ! ? | { } = ® © [ ]`
also any emoji. those worked before for certain

**Comment by c-probably-archived20260718** [comment]
fixed https://github.com/espterm/espterm-front-end/commit/190b1e6422ba0d480763529dcec99abd1ecbe881

**Comment by MightyPork** [comment]
works!
