### ISSUE TITLE
Vertical lines on light bg with chrome on Windows

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#160]
probably some nonsense with rounding again.
I haven't tried this, they're screenshots I received

one idea to try as a work-around could be to change the back-plane color based on the predominant background color, if there is one

![v11b vertical lines](https://user-images.githubusercontent.com/2041118/30295561-4a78e356-9741-11e7-9bb9-0b46c0787b87.png)

**Comment by MightyPork** [comment]
I can kinda reproduce this by zooming in chrome (and firefox)

**Comment by c-probably-archived20260718** [comment]
also happens in fullscreen mode on Android. I'm not sure what's causing it though

**Comment by MightyPork** [comment]
i've added a work-around that sets canvas bg to the most common bg of all cells, should do the trick for now
