### ISSUE TITLE
Weird gap under canvas

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#162]
got this after removing pretty much all styles - the gap is still there.

any ideas where it's coming from?

![screenshot_20170911_232008](https://user-images.githubusercontent.com/2041118/30297402-f7ab5fb2-9747-11e7-83ef-81fbcfb084cd.png)

**Comment by c-probably-archived20260718** [comment]
I don't see anything (the yellow part is the recolored `#screen` container)
<img width="457" alt="screenshot" src="https://user-images.githubusercontent.com/5412095/30297698-f38ec328-9748-11e7-8755-b1f3c6318191.png">

**Comment by MightyPork** [comment]
the padding is even on all sides. Or, well. so the stylesheet says and was the case with legacy screen

you also have it wider at the bottom

**Comment by c-probably-archived20260718** [comment]
oh that's the CSS line-height. `<canvas>` is an inline block so it adds that

**Comment by MightyPork** [comment]
Oh. that's stupid. and dev tools don't highlight that
