### ISSUE TITLE
Use rectangles to draw half- and full-block characters

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#175]
because e.g. my firefox uses some garbage font and it ends up like this:

![screenshot_20170915_085447](https://user-images.githubusercontent.com/2041118/30470102-adedcbae-99f3-11e7-84de-3856bb63e3ce.png)

this would be nice to also have for line drawing characters, but that seems to work more reliably than the half-blocks.

**Comment by c-probably-archived20260718** [comment]
What about box drawing/shading characters (▒)?

**Comment by MightyPork** [comment]
if you think that's doable, that would also be nice, but i thought it'd be too expensive

**Comment by c-probably-archived20260718** [comment]
nooo text rendering is the part that's most expensive; if we used bitmap fonts (see https://github.com/cpsdqs/sqio) this'd render the whole screen in less than ten milliseconds

**Comment by MightyPork** [comment]
well talking of that, I would totally dig this font from the old IBM PC
![ascii-vga](https://user-images.githubusercontent.com/2041118/30470461-23728da0-99f5-11e7-8182-8c8d9f2b6163.gif)
but it doesnt have almost any unicode so that'd look awful when mixed

**Comment by c-probably-archived20260718** [comment]
Terminus?

**Comment by MightyPork** [comment]
idk i don't really like terminus. maybe profont (but that also doesn't cover much)
objectively the ibm font is quite ugly, but _r e t r o_

maybe we could steal the front from cool-retro-term

**Comment by MightyPork** [comment]
ummm okay so it is using terminus xD

but the font is 300 kB

**Comment by c-probably-archived20260718** [comment]
Actually if you gzip it it's 50kB, which is... still huge
If you use only one style, it's 16kB gzipped, which is... still huge
You could of course make a fancy standalone client but I feel like that's not within the scope of this project

**Comment by MightyPork** [comment]
16 kB is not so bad, there is still a couple hundred kB left in the flash of the smallest module.
Bigger issue is the strain loading multiple files puts on the processor (that's why I put the Fontello font as inline data into the stylesheet). The browser goes berserk and tries to load all at once and there are max 4 connection slots available.

**Comment by MightyPork** [comment]
As for making a stand-alone client, once I add telnet, the whole browser thing can be switched off and people can use iTerm or whatever on their desktop

**Comment by c-probably-archived20260718** [comment]
Added most block drawing characters (except the quadrants) in https://github.com/espterm/espterm-front-end/commit/0520b043f8c7fa88f2947fe0c2c117593782aab0

**Comment by MightyPork** [comment]
works nicely! I'll add the remaining quadrants, just because

**Comment by c-probably-archived20260718** [comment]
~so~
~most quadrants won't draw for me~
<img width="511" alt="screenshot of quadrants not drawing" src="https://user-images.githubusercontent.com/5412095/30502572-18e65f8e-9a67-11e7-95f0-3fa0991d3907.png">

nevermind javascript screwed up

**Comment by MightyPork** [comment]
lolz

but that shouldn't happen? it has that cache busting thing already added in
![screenshot_20170915_224337](https://user-images.githubusercontent.com/2041118/30502639-6890bf2a-9a67-11e7-9a44-4554eff280d7.png)

**Comment by MightyPork** [comment]
fullscreen redraw with the dense shading character takes 100 ms. hopefully people don't do that a lot xD

**Comment by c-probably-archived20260718** [comment]
if that becomes an issue, we'll switch to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern

**Comment by MightyPork** [comment]
hmm it even has a pretty decent support

**Comment by MightyPork** [comment]
btw putting a block cursor over the block characters produces some hilarious animations
