### ISSUE TITLE
rainbow demo makes the logo text vanish

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#176]
because it uses background instead of box characters

![screenshot_20170915_085856](https://user-images.githubusercontent.com/2041118/30470250-37692b12-99f4-11e7-8ecf-68e291c106ee.png)

**Comment by c-probably-archived20260718** [comment]
fixed: 
<img width="991" alt="screenshot" src="https://user-images.githubusercontent.com/5412095/30499297-35d2c270-9a5a-11e7-95e6-3eb0de334b6e.png">
