### ISSUE TITLE
Don't show a gray screen forever if the server doesn't accept the connection

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#177]
Currently, it'll just show this and reload the page every few seconds
![screenshot](https://user-images.githubusercontent.com/5412095/30477100-58a1d1c2-9a0c-11e7-9419-fed1d30929aa.png)

**Comment by c-probably-archived20260718** [comment]
In conjunction with this, it may be good to have a better indicator for “you've been disconnected” than the flickering gif in the top-right corner which goes off-screen when you scroll

**Comment by MightyPork** [comment]
Yeah some overlay with "Reconnecting(flashing dots)" would be nice
The whole reconnect thing is a little rough atm,I think one of the timers
sometimes fires when it should be stopped and reloads it when it's no
longer needed

**Comment by c-probably-archived20260718** [comment]
I added this 
![screen showing disconnected](https://user-images.githubusercontent.com/5412095/30502133-460d546a-9a65-11e7-8642-9670c7bb7c69.png)

**Comment by MightyPork** [comment]
is it in git? I still have the old behavior when the esp restarts

**Comment by c-probably-archived20260718** [comment]
it is now

<img width="466" alt="yikes" src="https://user-images.githubusercontent.com/5412095/30502260-c85e2db8-9a65-11e7-9b57-397966005e3b.png">

**Comment by MightyPork** [comment]
what a mess xD
it works, with some glitches:
- the regular ajax spinner is still popping up with each request
- it flashes for like 2 segments and then hides again during the heartbeat polling

**Comment by c-probably-archived20260718** [comment]
well the code for setting the status screen is in term.js:9–14, change it all you want

**Comment by c-probably-archived20260718** [comment]
So about something related to this issue; why exactly does it _reload_ when the ping is successful?

**Comment by MightyPork** [comment]
i think it's from back when the initial data load was done via ajax and not by sending `i` to the WS.
now naturally the better solution would be to just re-open the socket

**Comment by MightyPork** [comment]
reloading the page also re-loads the window title that's atm not sent back with the initial load (`i`). but that not happening is a minor drawback
