### ISSUE TITLE
Split the monstrous screen class to smaller units

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#183]
but I'm not sure how ...

for start maybe we can at least have stuff like notification showing, beeping and setting labels elsewhere (ie. the entire thing that branches by the first letter of the update object)

**Comment by c-probably-archived20260718** [comment]
well it would certainly be nice if there were a way to not have to put everything external into global scope

(ES2015 modules is _still_ not well supported. Also, it would probably overload the server)

**Comment by MightyPork** [comment]
It goes through babel already, so if you think that's a way to make it cleaner...

**Comment by MightyPork** [comment]
or well that webpack thing. if the overhead is not too big

**Comment by c-probably-archived20260718** [comment]
about 2kb minus babel? (I didn't check how much webpack itself was)

**Comment by MightyPork** [comment]
i'll make an issue for that (bc i like issues :)

**Comment by MightyPork** [comment]
okay so I've split off themes and the color table for a start 
(and the `themes` module is for now in global scope for use by the color previews)

**Comment by c-probably-archived20260718** [comment]
this commit https://github.com/espterm/espterm-front-end/commit/9ccf9dd2cf1920fd143e199476efbd667175ac94

note that I might have inadvertently broken some things

**Comment by MightyPork** [comment]
that's a big one

i'll try to test it asap
