### ISSUE TITLE
Check if Webpack is feasible / try to use it

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#184]

**Comment by MightyPork** [comment]
really though I have 0 idea how this works, other than having used it when hacking on mastodon

**Comment by c-probably-archived20260718** [comment]
So webpack works fine on term.tpl, but all the other pages have HTML4-style inline scripts that use whatever they want so they break. What should be done about those?

**Comment by MightyPork** [comment]
I think this mostly boils down to `$` and `tr` and the `WiFi` object. Can they be injected to the global scope?

wificonn should be self-contained iirc

**Comment by MightyPork** [comment]
hmmmm app.js is now 93 kB vs 51 kB?

**Comment by MightyPork** [comment]
oh nvm that must be the demo. But it's still 17 kB larger

**Comment by MightyPork** [comment]
some observations: webpack's own overhead is about 4 kB (could be less if it didn't put tons of useless comments everywhere), the rest is due to... worse minified files?

**Comment by c-probably-archived20260718** [comment]
oh yeah I totally forgot to minify it

**Comment by c-probably-archived20260718** [comment]
So the 51 kB is outdated; the `work` branch is actually 68 kB. Webpack, minified, is 60 kB. I have no idea how that works.

**Comment by MightyPork** [comment]
right you are
can you push the minification? i'll try to get the other pages to work

**Comment by MightyPork** [comment]
did i mess something up?
![screenshot_20170917_214641](https://user-images.githubusercontent.com/2041118/30524315-b9e8df70-9bf1-11e7-993f-fc7ce27a3fd0.png)

**Comment by c-probably-archived20260718** [comment]
""works as intended""
fixed xD

**Comment by MightyPork** [comment]
looks like all works, but phpstorm decided it now doesn't like chibi and the short functions in utils.js (`qs`, `qsa`, `mk`) and marks everything as "not found" :/
