### ISSUE TITLE
Add a list of supported browsers to the readme

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#187]
- chrome
- chromium (naturally)
- mobile chrome
- opera (bc it's really just chrome)
- brave (ditto)
- firefox
- safari
- konqueror (against all odds)
- edge? i havent tried that

**Comment by c-probably-archived20260718** [comment]
edge works but—at least in BrowserStack—it's incredibly slow
servo does not work

meanwhile, I ~am going to install~ installed Windows 10

**Comment by c-probably-archived20260718** [comment]
Installed Windows ten; with Firefox and Edge: Firefox works fine, but Edge is reeeeally laggy. Currently figuring out why.
Apparently drawing takes ~780ms for 9 cells. It's absolutely ridiculous .-.

**Comment by MightyPork** [comment]
90 ms per cell? WHAAAAAT

well i dont think we can expect much from microsoft but that's pretty shitty

is it in a VM? I had some bad luck with windows 10 in virtualbox

**Comment by MightyPork** [comment]
we can just tell people not to use it :3

**Comment by c-probably-archived20260718** [comment]
Okay, here's a full report of the `draw` method:
- setup: <1ms
- generate update map: 60ms
- generate redraw map: 80ms
- draw backgrounds: 260ms
- draw characters: 380ms

I'd like to emphasize here that the first two steps are pure javascript

**Comment by MightyPork** [comment]
that's perfectly horrible

let's just say we don't support IE I guess

**Comment by c-probably-archived20260718** [comment]
this is Edge, it doesn't run on IE
but yes

**Comment by MightyPork** [comment]
btw microsoft owns https://modern.ie

....


yeah

**Comment by c-probably-archived20260718** [comment]
An IE-compatible version goes well beyond 376 kB with all those polyfills lol
So what's the list of unsupported browsers, to show a warning for?

**Comment by MightyPork** [comment]
a warning? ... i mean, why not. looks like it sucks in any flavour of IE / Trident / Edge and Opera Mini.
It _might_ work with android browser, i can't test that. Probably wont work on blackberry also

we can also have a Cookie Notice after I implement session cookies LOL

the supported browser list is just so I can point people to it when they ask
