### ISSUE TITLE
Soft keyboard input duplicates backspace

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#189]
Happens in Chrome Android and the undebuggable Firefox Android. Caused by https://github.com/espterm/espterm-front-end/commit/09d3fff59da5bfc3f0781acddd54a05fa0015cbe

**Comment by MightyPork** [comment]
huh do you think this can be fixed? otherwise maybe it's better to forego ff mobile compatibility if it ruins it for everyone :/

**Comment by c-probably-archived20260718** [comment]
I have an inkling as to what the issue is, but further debugging needed™

**Comment by c-probably-archived20260718** [comment]
wow that was easy to fix (df4c75b)
