### ISSUE TITLE
Demo doesn't work: Uncaught TypeError: t.child.off is not a function

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#190]
![screenshot_20170923_023421](https://user-images.githubusercontent.com/2041118/30768437-c433b5b2-a007-11e7-81b2-b6e52be8f9b8.png)

![screenshot_20170923_023416](https://user-images.githubusercontent.com/2041118/30768438-c6de3d46-a007-11e7-8bfb-789cce410a60.png)

![screenshot_20170923_023356](https://user-images.githubusercontent.com/2041118/30768440-c94d6c6e-a007-11e7-8ee5-c14c5db50f0d.png)

also looks like it doesn't draw the whole background, just pieces (must be because of the crash)

**Comment by c-probably-archived20260718** [comment]
Fixed the error but not the background issue https://github.com/espterm/espterm-front-end/commit/91c17e0fc38ab634f3ce7fd890a54c08dee72b7e

**Comment by MightyPork** [comment]
That was quick

**Comment by c-probably-archived20260718** [comment]
Also fixed the background issue. For some reason, the palette is switched from 0 to 1 and then 0 again halfway through, and I also wasn't clearing the drawnScreen when the palette is switched. It now renders correctly but the screen flashes black for a moment now
