### ISSUE TITLE
Update demo to use UTF-8 data encoding & off-scale FG/BG

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#191]
- Screen data object now uses UTF-8 codepoints instead of 2B and 3B. Each data codepoint is `UTF8(n+1)` (to avoid \0 in the string).
- The old encoding is used only for mouse reports now, because it's easier to parse on the server.
- Attribs word is now 2-byte (but can be encoded in a single code point if small enough)
- All characters have default background and foreground, unless bits 8, resp. 9 are set in attrs. Those bits make the renderer use the bg and fg fields
- Attrs bit 10 signifies INVERSE
- Bit 14 of global attribs signifies REVERSE_VIDEO (flip fg/bg). This was previously done server-side, not possible anymore because of off-scale fg and bg.
- default fg and bg are set using %default_fg% and %default_bg%, use the format 0-255 or TrueColor+256
- pre-defined fg/bg themes are prepared in themes.js but the UI for selecting them is not yet implemented. Those will be used to copy hex from, rather than to remember theme number like with normal themes.

**Comment by c-probably-archived20260718** [comment]
Done https://github.com/espterm/espterm-front-end/commit/c68017bd4ad387786dd17b213be9bdd29fe4c0ea
