### ISSUE TITLE
Selecting is messed up

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#193]
idk what exactly happened there yet, probably some logic that assumes fg and bg hold the current color but they can be 0,0 when bits 8 and 9 (HAS_FG, HAS_BG) are not 1

![screenshot_20170924_033021](https://user-images.githubusercontent.com/2041118/30778540-c4fd3ae6-a0d8-11e7-8824-c4e20d5afc0a.png)

**Comment by c-probably-archived20260718** [comment]
aaah what happened espterm-emulator is no longer compatible

**Comment by c-probably-archived20260718** [comment]
Fixed—you accidentally made it look up the selection colors in the palette https://github.com/espterm/espterm-front-end/commit/a196f9a9de50010604ad3cbd00e775f1b8f30a7d

**Comment by MightyPork** [comment]
ah yeah i broke it real good lol
but it shan't happen again at this scale, utf8 data fields can stretch to 2.5 bytes
