### ISSUE TITLE
"Waiting for server..." overlay disappears before screen init response is received

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#195]
so the old content flashes briefly before it's redrawn

**Comment by c-probably-archived20260718** [comment]
For that matter, sometimes there's also an erroneous half-second or so of “Re-connecting” after reconnecting

**Comment by c-probably-archived20260718** [comment]
Should be fixed with https://github.com/espterm/espterm-front-end/commit/9c4027d2d1a42f4e94a45f7302fb3032fc4709f6
