### ISSUE TITLE
try to use passive event listeners

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#197]
not sure if this helps anything, but chrome is complaining about those with verbose logging enabled

![screenshot_20170924_180728](https://user-images.githubusercontent.com/2041118/30784312-4e67e964-a153-11e7-9029-bb50dc1d816f.png)

**Comment by c-probably-archived20260718** [comment]
Can't make `wheel` passive because passive event listeners can't preventDefault. Also why are we using the non-standard `mousewheel`?

**Comment by MightyPork** [comment]
alright, just reporting what i see :p

i'm recycling what i used earlier, so it must be from some old project ...

**Comment by c-probably-archived20260718** [comment]
There's not a lot of event listeners listed in that violation message that can be passive
in fact, there's only one
https://github.com/espterm/espterm-front-end/commit/16436a9a9886a692803785bfc000ee721d7d7a7b
