### ISSUE TITLE
compress HTML before shipping

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#202]

**Comment by c-probably-archived20260718** [comment]
On the topic of reducing size, here's a report of all the things:
- total size of `out`: 230966
  - css: 35437
  - img: 22694
    - large images:
      - vt100.jpg (11088)
      - cvut.svg (8998, can be compressed a bit more with svgo)
  - js: 90555
    - large source files:
      - screen_renderer.js (23787)
      - chibi.js (17580)
      - screen.js (17249)
  - html: 74814
    - large pages:
      - help.html (36384, can't be compressed well (90%?))
      - cfg_term.tpl (13295, ditto ^)

**Comment by MightyPork** [comment]
I think we could get rid of chibi, or gut it to some extent. I've already
considered rewriting it or looking for even smaller alternatives

**Comment by MightyPork** [comment]
the point of compressing html is not so much about the total file size btw,
as about how much work the processor must undertake to serve it - it sends
it in 2kB chunks with chunked encoding
