### ISSUE TITLE
API for controlling ESP8266 GPIOs remotely

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#215]
toggle pins, set multiple at once, read pins, read ADC...

**Comment by schneemaier** [comment]
Would be really useful feature. Today i would be able to use it to reset my remote mini computer, instead of waiting till tomorrow evening when i get there :)

**Comment by schneemaier** [comment]
Any new release expected in the near future which could include this feature?

**Comment by MightyPork** [comment]
I wouldn't say "expected", but I've just submitted the GEX thesis for review (see https://www.ondrovo.com/cvut/dp and https://github.com/gexpander, you might find it interesting too), so if things go smoothly with the defense I get my diploma before the end of June and then I can work on ESPTerm again. There wasn't any activity on this project because of GEX...

**Comment by schneemaier** [comment]
Nice one! Will look into more detail

**Comment by schneemaier** [comment]
I know it is summertime :) but any chance that there will be update on this feature in the the next 4-6 weeks or a feature to do ota update of the firmware?

Thanks

**Comment by MightyPork** [comment]
I've fallen victim to Another Side Project (https://datatable.directory/), but I didn't forget. I have this bad habit of having too many new projects and too little time. I hope to get to it soon :`]

**Comment by MightyPork** [comment]
Okay, I decided to give this a try this weekend. So far it looks like I'll be able to provide API to control GPIO4, GPIO5 and GPIO16. @schneemaier is configuring the initial levels after boot important to you? If not (all go to 0 at startup), this could be added without any config or UI changes at all

**Comment by schneemaier** [comment]
Thanks for the try. Unfortunately I use ESP8266-01 board and that only has gpio 0 and 2 available. As I don't use gpio2 debug output hoped for using that...

Output level is important in the final application as it controls the reset pin and it need to be high. (If it is not possible to control the initial state I can use additional transistor to invert it)

**Comment by MightyPork** [comment]
okay, I'll see what can be done about that. 

It should be possible, just count with a burst of UART output on GPIO2 during boot, even if you set it as GPIO, that can't be easily prevented

**Comment by MightyPork** [comment]
Now we have an API and also a GUI page:
https://github.com/espterm/espterm-firmware/releases/tag/2.4.0-pre2
