### ISSUE TITLE
Recolor screen margin

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#216]
Especially noticeable in this screenshot:
<img width="247" alt="screenshot of white background but black screen margin" src="https://user-images.githubusercontent.com/5412095/30980748-6e1bb98e-a482-11e7-92a2-281d98bd46b9.png">
The screen margin doesn't update its color with the screen backgrounds or themes and can thus kind of break the seamless style.

Possible solutions:
- [ ] Don't fix it at all
- [ ] Set it to the default background and be done with it
- [ ] Set it to the average background color
- [x] Set it to the adjacent cell background color (ComputerCraft does this, or at least it did last time I used it which is like 2015)

**Comment by MightyPork** [comment]
idk ... muted adjacent color sounds fun

talking of changing color, there can also be an OSC to change the border color...

**Comment by c-probably-archived20260718** [comment]
muted? The adjacent cell color thing meant that the cells along the perimeter would essentially just get bigger

**Comment by MightyPork** [comment]
yeah I don't really like that

something like this:
![sss](https://user-images.githubusercontent.com/2041118/30981530-efc00bdc-a484-11e7-8168-f1e03eb18189.png)

**Comment by c-probably-archived20260718** [comment]
could also do this with almost zero CSS hacks (at least in Safari, Chrome's backdrop-filter is still incredibly glitchy but behind a flag so no one will notice)
![an image. can't be bothered to do an alt text. sorry screen readers](https://user-images.githubusercontent.com/5412095/30981722-7a9897c4-a485-11e7-8b3d-a1db0ace7380.png)

**Comment by MightyPork** [comment]
that wouldn't be bad

**Comment by c-probably-archived20260718** [comment]
Implemented https://github.com/espterm/espterm-front-end/commit/aa41cf512e03946212106af6afb3d974e362463d

**Comment by MightyPork** [comment]
i'll have a look - after making back-end compile again xD

**Comment by c-probably-archived20260718** [comment]
haha, blurry
<img width="962" alt="blurry margins with vim" src="https://user-images.githubusercontent.com/5412095/30983306-57c29fd8-a48a-11e7-9be8-8f9ce3a9396f.png">

**Comment by MightyPork** [comment]
looks nice
but u may wanna fix that horrible overlapping triangle :p

**Comment by c-probably-archived20260718** [comment]
you mean the powerline symbols? that's the font's fault

**Comment by MightyPork** [comment]
idk what's a powerline but looks like it could be drawn using a polygon...
![screenshot_20170928_202328](https://user-images.githubusercontent.com/2041118/30983497-e7eff93e-a48a-11e7-982d-8699d333729e.png)

**Comment by c-probably-archived20260718** [comment]
hm good idea, though I seriously doubt anyone would use vim with powerline (or in this case, airline) in ESPTerm xD

**Comment by MightyPork** [comment]
I mean no, but they're nice symbols :P
I'll add them together with the block drawing characters to a new codepage
