### ISSUE TITLE
Add some light themes

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#221]
(custom themes would also work, but that's effort)

e.g.
- Tango Light
- default xterm theme
- Solarized Light

This would mostly involve swapping colors 0/7 and 8/15 and darkening the rest

**Comment by MightyPork** [comment]
umm we have light themes (and xterm default theme is dark???)
![spectacle x30941](https://user-images.githubusercontent.com/2041118/31015726-e5c275be-a521-11e7-90cb-d141c55f4341.png)

**Comment by c-probably-archived20260718** [comment]
yeah, but every app still assumes that 0 is the background color. I guess this can be a wontfix.

Also
![xterm on xquartz](https://user-images.githubusercontent.com/5412095/31016167-f53c234e-a523-11e7-99f2-03b8c960f075.png)

**Comment by MightyPork** [comment]
huh? send a PR to your apps I guess...
dont really mind if you add more themes tho. blows up the code a bit but it's not something dramatic

**Comment by MightyPork** [comment]
![screenshot_20170929_144303](https://user-images.githubusercontent.com/2041118/31016332-8712db14-a524-11e7-88ad-4c254bebeb04.png)

**Comment by MightyPork** [comment]
i've added solarized light and high-contrast dark, add the others if you find them...
