### ISSUE TITLE
blurry padding looks funny in corners

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#222]
![screenshot_20170929_194918](https://user-images.githubusercontent.com/2041118/31028719-5892d5de-a54f-11e7-8623-47f9887f0056.png)

**Comment by c-probably-archived20260718** [comment]
Yeeeah that's because those are two divs; I don't really know how one would go about making that one xD

**Comment by MightyPork** [comment]
it's not so bad without the blur tbh ![screenshot_20170929_200332](https://user-images.githubusercontent.com/2041118/31029240-4c5039b8-a551-11e7-8e9b-29f63b06a7be.png)

**Comment by c-probably-archived20260718** [comment]
feel free to remove the backdrop-filter without the `-webkit-` prefix then

**Comment by MightyPork** [comment]
do you think they could be bevelled like this? (idk how to do that)
![screenshot_20170929_200533](https://user-images.githubusercontent.com/2041118/31029332-9832cc2e-a551-11e7-97b6-076fe6b92b00.png)

**Comment by c-probably-archived20260718** [comment]
Yes. It would be the hack of the century. But not the worst hack in this project :P

**Comment by c-probably-archived20260718** [comment]
nevermind it doesn't work

**Comment by MightyPork** [comment]
aww

**Comment by c-probably-archived20260718** [comment]
okay I did make one that works
https://codepen.io/anon/pen/MEoGYP
but only in Safari .-.

**Comment by MightyPork** [comment]
i had high hopes for that thick border hack but it blurs even under transparent :c

**Comment by MightyPork** [comment]
chrome blurs even outside clip-path? wtf
