### ISSUE TITLE
soft kb should not open on canvas tap if mouse reporting is enabled

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#224]
quoting

>On Android the soft KB comes up as soon as I touch the terminal window - no mouse event is generated
I tested this on a Tablet and a Phone - both with Android 6.01 & Chrome
AMIduos Android Emulator on W10 Surface Pro - same problem
This definitely worked in an older version
>
> Bug ->  the mouse function is broken on Android due to soft KB popping up
>
> I digged out my Surface Pro, which runs an older W10 and has a touchscreen
Chrome works with a mouse, but not on touch - other tabs works fine with touch in Chrome
Firefox works fine with touch & mouse
Edge is slow as hell, but displays ok -  works with touch
Soft KB only comes up when Icon is clicked - ok

(edge report checks out xD)

**Comment by c-probably-archived20260718** [comment]
oh yeah I guess it shouldn't do that lol
I'll fix that after I do sass things

**Comment by MightyPork** [comment]
okay cool
also any idea what's up with the chrome touch events he mentions?

**Comment by c-probably-archived20260718** [comment]
well I don't really understand what “does not work on touch” is supposed to mean xD

**Comment by MightyPork** [comment]
hes been testing the screen, I assume it's about mouse reporting not firing for touches
that being old surface with windows 10 leads me to believe the chrome isn't exactly 63, if that's any hint
