### ISSUE TITLE
Add a non-English locale to test if i18n works

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#232]
the locale would be selected using an env variable at build time

**Comment by c-probably-archived20260718** [comment]
It works but some words are clipped
<img width="806" alt="Administratorpasswort is too long" src="https://user-images.githubusercontent.com/5412095/31048438-407acde8-a61d-11e7-831b-a193ce467ce4.png">

**Comment by MightyPork** [comment]
\*ahem* maybe don't have such long words :P

**Comment by MightyPork** [comment]
okay so the label width could of course be increased, but some things are just ridiculous:

![screenshot_20170930_213506](https://user-images.githubusercontent.com/2041118/31048867-4a57b0d8-a627-11e7-9319-673e2bcb9b5c.png)

can some of the longest labels be shortened? I'll then make DE binaries with the next release (and also CS)

**Comment by c-probably-archived20260718** [comment]
uhh, not really, but I guess you could truncate

**Comment by MightyPork** [comment]
gave u some more room there
also we now have Czech, yay!
![screenshot_20170930_234433](https://user-images.githubusercontent.com/2041118/31049731-67d41ef0-a639-11e7-80b3-bdcc5f9221e7.png)
