### ISSUE TITLE
Color triangle does not work depending on screen Y

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#236]
It's really strange; sometimes it works, and then you scroll down or up a bit and it hits a threshold where it just doesn't do anything when you click and drag. Tested in Safari. Also what is that sorcery—SVG with a pixelation filter or something? xD
It can't be inspected, it excuses itself and disappears when you open dev tools :(

**Comment by MightyPork** [comment]
yeah it's somewhat buggy - I've converted the library to ES6, but the bugs survived apparently (if not multiplied)

i think it's not doing a v good job at figuring out the relative mouse coordinate

**Comment by MightyPork** [comment]
oh and it's a canvas

**Comment by MightyPork** [comment]
wow what a shitshow

it measures the element offset on load and then thinks it's fixed forever (?)

**Comment by MightyPork** [comment]
removed like 20 lines of javascript and used getboundingclientrect instead, seems to work ok
