### ISSUE TITLE
Some weird black rectangle next to screen

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#241]
![screenshot from 2017-10-03 09-15-02](https://user-images.githubusercontent.com/2041118/31114225-4594285e-a81d-11e7-9069-b58454346de4.png)

I haven't reproduced this yet, got it in a report. No idea wtf it is

 chrome (Version 61.0.3163.100 (Official Build) (64-bit))

**Comment by c-probably-archived20260718** [comment]
any other details?

**Comment by MightyPork** [comment]
Not really, I'm asking them to inspect it. Added the chrome version... It's
latest 'work'

**Comment by MightyPork** [comment]
It's all really odd, I'm not near the pc to check it atm but I've never seen anything like that
![screenshot from 2017-10-03 11-10-32](https://user-images.githubusercontent.com/2041118/31118546-1291dd28-a82e-11e7-9865-32dc4b126ad2.png)
![screenshot from 2017-10-03 11-11-00](https://user-images.githubusercontent.com/2041118/31118547-1293a752-a82e-11e7-8d4c-9ca11129e9b2.png)
![screenshot from 2017-10-03 11-11-26](https://user-images.githubusercontent.com/2041118/31118548-12940b16-a82e-11e7-80af-cee7621ec201.png)

**Comment by MightyPork** [comment]
(he tried deleting some stuff, for whatever reason)

**Comment by c-probably-archived20260718** [comment]
Only reason I can think of is that the blur on the screen margins is messing up the renderer

**Comment by MightyPork** [comment]
We could make it toggleable xD
I really don't get why it's all so weirdly asymmetrical tho. There
shouldn't be any dark/light region around the screen (or to the side)...

**Comment by c-probably-archived20260718** [comment]
No we should know if it's actually causing it before doing anything like that lol

**Comment by MightyPork** [comment]
ikr lol
I didn't see any such bug yesterday when I tested that release...
And it's not some cached asset thing either, there's a cache busting fix
already

**Comment by MightyPork** [comment]
got a report that this can be fixed by adding the background color to body
it doesn't really make sense, but if it works...

**Comment by MightyPork** [comment]
i can't reproduce it and we have a work-around added, so i'll close this
