### ISSUE TITLE
german locale improvements

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#243]
quoting

at WLAN ; " druecke Bestaetigen druecken"  should mean only " druecke Bestaetigen" 
at Terminal : "Serienportparameter" should mean " Serieller Port Parameter"

idk what any of that means

**Comment by c-probably-archived20260718** [comment]
I think I did fix the first one

**Comment by MightyPork** [comment]
quite possible, he's been testing beta2

**Comment by c-probably-archived20260718** [comment]
ce1bda3, fixed

**Comment by MightyPork** [comment]
cool ty
