### ISSUE TITLE
Demo bugs

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#244]
![ggg](https://user-images.githubusercontent.com/2041118/31176868-a0817e54-a914-11e7-835f-724b3eac2f7e.PNG)
also the color is gray by default after this, should be 7 or default..
- local echo lacks Exit button

- typing sudo auto-completes "github" immediately, no way to enter the sandwich command
- make also auto completes github as the target
- same for the "theme" command

possible improvements>
themes command output is imo quite overwhelming and hardly gives you an idea of how the themes feel
mouse command doesnt showcase that we can also track mouse motion and drag/drop

**Comment by c-probably-archived20260718** [comment]
espterm/espterm-front-end@fcfd351
I added the exit command, fixed an issue with autocomplete appearing when it shouldn't, but I don't get what you mean by “auto-completes "github" immediately”

**Comment by MightyPork** [comment]
well I typed "make " and it started typing github and then executed it (or
something)

You can see it on the demo page

**Comment by c-probably-archived20260718** [comment]
can't reproduce—the only reason why it would do that is if you pressed the button below

**Comment by MightyPork** [comment]
huh that's odd. Maybe the button was focused and space pressed it, that's
pretty sucky

**Comment by c-probably-archived20260718** [comment]
Here's a fancier mouse demo
![screenshot](https://user-images.githubusercontent.com/5412095/31191873-d8c66826-a93f-11e7-8e1b-34fa0175fdab.png)

**Comment by c-probably-archived20260718** [comment]
I don't know what to do about `themes`, any ideas?

**Comment by MightyPork** [comment]
looks great!!

**Comment by MightyPork** [comment]
idk.

one idea - show a fullscreen preview and let user flip through them, "q" for exit or something
but it'd be nice to have their names in the themes array for that... they're now only in the html select box

**Comment by MightyPork** [comment]
a thing about this theme preview tho ... the 0-15 themes play some role, but even greater effect have the default colors. there are far too many combinations to just show a big preview of everything

**Comment by c-probably-archived20260718** [comment]
I'll tackle that tomorrow then. If I'm feeling exceptionally bored I might accidentally add an RGB color picker inside the terminal

**Comment by MightyPork** [comment]
just please don't accidentally add sixel lol

**Comment by c-probably-archived20260718** [comment]
if I do all the code will be grafted onto the renderer in the demo.js file xD
