### ISSUE TITLE
possibility to have an image background

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#246]
> a background picture from some external server - giving a room layout map or piping diagram
URL should be definable dynamically by a controlmessage  from the micro

The idea is to load an image behind the canvas as a background.

@cpsdqs do you think the renderer can be augmented to optionally don't draw default background and instead leave it transparent?

**Comment by c-probably-archived20260718** [comment]
technically you could even draw the background with canvas, yes

**Comment by c-probably-archived20260718** [comment]
I don't know why one would want this but it's possible now ¯\\\_(ツ)_/¯
<img width="1022" alt="screen shot 2017-10-06 at 23 30 47" src="https://user-images.githubusercontent.com/5412095/31299387-72882990-aaee-11e7-987b-4c85a58a88f4.png">

**Comment by MightyPork** [comment]
the "why" is simple :P

- seen those? this is for the colours

![](https://upload.wikimedia.org/wikipedia/commons/e/ee/%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0_%D0%98%D0%9C_02.jpg)

ok, a more likely example:

![](http://www.genlogic.com/partners/cct_engine_big.jpg)

**Comment by c-probably-archived20260718** [comment]
huh fair enough. Well, if you add it to the update string you can now just set `termScreen.backgroundImage` to the URL and everything should work fine (might need some CSS to fix scaling though)
