### ISSUE TITLE
Color settings for control buttons

### ISSUE THREAD

**Issue by plachta11b** [espterm/espterm-firmware#249]
Feature request: Add color changeable buttons in Terminal settings->Initial Settings->button colors for games in terminal. It can be useful for some applications. What about ability to add user CCS inside settings? This feature could bring interesting hacks for custom projects.

**Comment by MightyPork** [comment]
good idea, i think we should add this

**Comment by c-probably-archived20260718** [comment]
Client-side support added (for colored buttons): https://github.com/espterm/espterm-front-end/commit/ce46ad7e963ff072e35acca1ae1604ccb0c91702

**Comment by MightyPork** [comment]
kinda. i think this should be appended to the buttons update topic, it'll usually change together with the labels

**Comment by c-probably-archived20260718** [comment]
Yeah you can just split each entry by `\x02` or just have the array repeat again for the color values or something and have the color there (you do need a null value though)
Also, if we add a user CSS feature, we could also consider adding user JS as well (and also add an `espterm` wrapper object or something in the global scope)

**Comment by MightyPork** [comment]
how about each button text field starts with the color (two words, like the bg and fg colors) followed by the text and terminated by 0x01?

I don't have storage for user CSS, the entire RW area is 2kB large and already half used (though i imagine it could be expanded if need be)

**Comment by c-probably-archived20260718** [comment]
Sure, as long as it has a null color

**Comment by MightyPork** [comment]
null color? does that mean "use default"?

**Comment by c-probably-archived20260718** [comment]
yes (null as in `button.style.background = null`)

**Comment by MightyPork** [comment]
? ![screenshot_20171018_215327](https://user-images.githubusercontent.com/2041118/31739615-c8754126-b44e-11e7-93a0-40fb79997ba0.png)

**Comment by c-probably-archived20260718** [comment]
(what are you asking? xD)

**Comment by MightyPork** [comment]
still not sure what you mean by null background ...

**Comment by c-probably-archived20260718** [comment]
I meant you set the style attribute's background to null such that it falls back to whatever you set in the stylesheet

**Comment by MightyPork** [comment]
...hmm
there can be nothing in the stylesheet, if we always send a color --- and support 24bit

**Comment by MightyPork** [comment]
![screenshot_20171030_204925](https://user-images.githubusercontent.com/2041118/32192227-df1c9f5a-bdb3-11e7-958a-27da2cdd4666.png)
