### ISSUE TITLE
Lower number of buttons

### ISSUE THREAD

**Issue by plachta11b** [espterm/espterm-firmware#250]
How do i can change number of buttons? There are only two buttons in live demo and it looks much more cooler. After leaving button label and button command blank and clicking "Apply!" this message appear "Validation errors for: ". Typing number 0 into button command unexpectedly resulting in blanked input after applying change.

**Comment by MightyPork** [comment]
lowering number of buttons is not currently implemented in the back-end, but it's planned - see #233

the other part sounds like a bug - though leaving the label empty should result in a grayed-out look of button

**Comment by MightyPork** [comment]
the validation error is fixed in work, will be in the next release
