### ISSUE TITLE
clone issue

### ISSUE THREAD

**Issue by mwolfeu** [espterm/espterm-firmware#256]
With --recursive, the git clone reports:
Submodule 'front-end' (git@github.com:espterm/espterm-front-end.git) registered for path 'front-end'
Submodule 'libesphttpd' (git@github.com:MightyPork/libesphttpd.git) registered for path 'libesphttpd'
Cloning into 'front-end'...
Permission denied (publickey).
fatal: Could not read from remote repository.

"git submodule update" fails similarly.   

Can these be made public so a key is not required?

**Comment by MightyPork** [comment]
They are public, you need to add your ssh key to GitHub, or clone without
recursive, edit .git/config to use https paths, and then 'submodules init'.

The use of ssh makes it work without constantly asking for a password when
we push. Hope this helps
