### ISSUE TITLE
double size lines

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#65]
http://vt100.net/docs/vt102-ug/chapter5.html#S5.5.2.19

this may now be possible with the canvas renderrer, but it'll complicate the code quite a bit so maybe rather not

**Comment by c-probably-archived20260718** [comment]
The backend code shouldn't become that complicated—xterm just stops moving the cursor when it reaches the end of the screen, it doesn't even wrap it, or delete the now invisible screen data. Could probably have an array of 25 uint8's containing flags for each line and just send that as another topic to the client. And rendering it would then be pretty simple

**Comment by MightyPork** [comment]
mm I think it won't be so bad indeed. If you add it to the front-end, I'll add the backend support

The topic could be more compact, e.g. (only non-normal lines):
(count)(line)(line)(...

line = attrs|(line<<3)

with attrs being 3 bits: double width, upper of dual height, lower of dual height

**Comment by c-probably-archived20260718** [comment]
https://github.com/espterm/espterm-front-end/commit/f61d861883c59a6a79efd740c0a3ed0784d51ebc
<img width="578" alt="screenshot" src="https://user-images.githubusercontent.com/5412095/32634340-6bc45bb0-c5ab-11e7-9adf-f7b468ef3c3b.png">
